baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Mandolyn Harkness'
theme = "notrack"

[params]
author = 'Mandolyn Harkness'
siteHeading = 'Mandolyn Harkness'
mainSections = ['blog']

[params.social]
github = 'mjharkn'
email = 'mjharkn@clemson.edu'